name: campus_navigation
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map and location packages
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_map_marker_popup: ^8.1.0
  flutter_polyline_points: ^3.1.0
  flutter_compass: ^0.8.0
  http: ^1.5.0
  carousel_slider: 4.2.1
  share_plus: ^7.2.0
  video_player: ^2.6.0
  vector_math: ^2.1.4
  google_fonts: ^4.0.4
  flutter_dotenv: ^5.0.2
  smooth_page_indicator: ^1.0.0
  lottie: ^2.3.2
  webview_flutter: ^4.2.1
  permission_handler: ^10.4.0
  flutter_inappwebview: ^5.7.2
  camera_web: ^0.3.5
  sensors_plus_web: ^1.1.2
  shared_preferences: ^2.2.3
  shared_preferences_web: ^2.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/buildings/
    - assets/videos/
    - assets/ar_direction.html
    